# Generated by Django 4.2.6 on 2024-01-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0002_region_wiki_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('iso2', models.CharField(max_length=5)),
                ('iso3', models.CharField(max_length=5)),
                ('numeric_code', models.CharField(max_length=10)),
                ('phone_code', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=10)),
                ('flag', models.SlugField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region')),
            ],
        ),
    ]
