# Generated by Django 4.2.6 on 2024-01-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
    ]
