# Generated by Django 4.2.6 on 2024-02-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_region_wiki_data_id'),
        ('countries', '0002_remove_country_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='region.region'),
            preserve_default=False,
        ),
    ]
