# Generated by Django 4.2.6 on 2024-01-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='wiki_data_Id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
